### ISSUE TITLE
Start-up error

### ISSUE THREAD

**Issue by nacimgoura** [codsen/detergent#18]
Hello,
Thank you for the recent update of detergent :smiley: 
But now I can't launch my application anymore, I have this error at startup : 
```
Error: Cannot find module './enforced-numeric-entities-list.json'
at Function.Module._resolveFilename (module.js:489:15)
at Function.Module._load (module.js:439:25)
at Module.require (module.js:517:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/home/ngoura/Documents/projet/nacim/node_modules/detergent/es5/detergent.js:9:18)
at Module._compile (module.js:573:30)
at Object.Module._extensions..js (module.js:584:10)
at Module.load (module.js:507:32)
at tryModuleLoad (module.js:470:12)
at Function.Module._load (module.js:462:3)
at Module.require (module.js:517:17)
at require (internal/module.js:11:18)
```
I respect the new syntax 
`
import { detergent } from 'detergent';
`
and I get the result in res.

Thank you for your help!

**Comment by revelt** [comment]
Sorry about that. Please check the patch release `3.1.1` and close if solved.

For posterity, many libraries and sources advise to put compiled code into some folder like `/dist/` but that's a dodgy idea because if source sits in the root and references any external files in the root, their references have to be changed from same folder to "go up one level". Babel won't do that, hence this issue. I assumed Babel would check file references but it won't. Furthermore, there's move to ES6 modules, which can be produced via Rollup, but npm hasn't acknowledged such field ("module") in official package.json documentation.. Once that's set up, there will be three files in root..

**Comment by nacimgoura** [comment]
Yeah, it solved my problem.
thanks :wink: 
I close this issue!
